### ISSUE TITLE
Stake Management account not connected and no data available

### ISSUE THREAD

**Issue by fioreb** [1Hive/celeste-contracts#20]
We need designs and implementation for:
- Stake management when there isn't an account connected 
- "No data available" illustration

**Comment by fioreb** [comment]
Here you can find the design:

https://www.figma.com/file/P06HTzSyb9hExJVpwaUPmA/Honey-Pot-2.0?node-id=2644%3A17206

Let's use the same component that we have for the Faucet when the account is not connected.

**Comment by rperez89** [comment]
closed by https://github.com/1Hive/honey-pot/pull/241
